Using ver 9.44 of go AND bypassing operations in .lagoon.yml

diff --git a/.lagoon.yml b/.lagoon.yml
--- a/.lagoon.yml
+++ b/.lagoon.yml
@@ -29,100 +29,100 @@ tasks:
           echo "Creating a initial pending deployment status."
           ./dev-scripts/lagoon-set-gh-deploy-status.sh "in_progress"
         service: cli
-    - run:
-        name: If drupal is not installed
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    # - run:
+    #     name: If drupal is not installed
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ]; then
-            # Install and set the admin password to a Lagoon variable if it exists.
-            if [[ -n $PR_DRUPAL_PWD ]]; then
-              drush si --existing-config -y --account-pass=$PR_DRUPAL_PWD
-            else
-            # Otherwise install and let drush generate a password.
-              drush si --existing-config -y
-            fi
+    #       if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ]; then
+    #         # Install and set the admin password to a Lagoon variable if it exists.
+    #         if [[ -n $PR_DRUPAL_PWD ]]; then
+    #           drush si --existing-config -y --account-pass=$PR_DRUPAL_PWD
+    #         else
+    #         # Otherwise install and let drush generate a password.
+    #           drush si --existing-config -y
+    #         fi
 
-            # Practice shows that the cache needs to be cleared to avoid
-            # configuration errors even after a site install.
-            drush cr
-          fi
-        service: cli
-        shell: bash
-    - run:
-        name: drush deploy
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    #         # Practice shows that the cache needs to be cleared to avoid
+    #         # configuration errors even after a site install.
+    #         drush cr
+    #       fi
+    #     service: cli
+    #     shell: bash
+    # - run:
+    #     name: drush deploy
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          if [[ -f config/sync/system.site.yml ]]; then
-            echo "Config detected, doing a drush deploy"
-            drush deploy
+    #       if [[ -f config/sync/system.site.yml ]]; then
+    #         echo "Config detected, doing a drush deploy"
+    #         drush deploy
 
-          # Purge all varnish cache to make sure
-          # that new changes will come through
-          # eg. js assets.
-          echo "...and clearing the external cache."
-          drush cache:rebuild-external -y || true
-          else
-            echo "No config detected, clearing cache"
-            drush cr
-          fi
-        service: cli
-    - run:
-        # We need this because if we create the directory before volume mount
-        # it will be gone.
-        name: Create module upload directory in public files
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    #       # Purge all varnish cache to make sure
+    #       # that new changes will come through
+    #       # eg. js assets.
+    #       echo "...and clearing the external cache."
+    #       drush cache:rebuild-external -y || true
+    #       else
+    #         echo "No config detected, clearing cache"
+    #         drush cr
+    #       fi
+    #     service: cli
+    # - run:
+    #     # We need this because if we create the directory before volume mount
+    #     # it will be gone.
+    #     name: Create module upload directory in public files
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          if [[ ! -d "web/sites/default/files/modules_local" ]]; then
-            echo "Creating directory for module uploads"
-            mkdir web/sites/default/files/modules_local
-          fi
-        service: cli
-    - run:
-        name: Import translations
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    #       if [[ ! -d "web/sites/default/files/modules_local" ]]; then
+    #         echo "Creating directory for module uploads"
+    #         mkdir web/sites/default/files/modules_local
+    #       fi
+    #     service: cli
+    # - run:
+    #     name: Import translations
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          drush locale-check
-          drush locale-update
-        service: cli
-    - run:
-        name: Create test users
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    #       drush locale-check
+    #       drush locale-update
+    #     service: cli
+    # - run:
+    #     name: Create test users
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          # Only create test users if they do not exist already.
-          if editor_user=$(drush sqlq 'select * from users_field_data where name = "editor"') && [ -z "$editor_user" ]; then
-            drush user:create editor --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'editor' editor
+    #       # Only create test users if they do not exist already.
+    #       if editor_user=$(drush sqlq 'select * from users_field_data where name = "editor"') && [ -z "$editor_user" ]; then
+    #         drush user:create editor --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'editor' editor
 
-            drush user:create administrator --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'administrator' administrator
+    #         drush user:create administrator --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'administrator' administrator
 
-            drush user:create mediator --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'mediator' mediator
+    #         drush user:create mediator --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'mediator' mediator
 
-            drush user:create local_administrator --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'local_administrator' local_administrator
+    #         drush user:create local_administrator --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'local_administrator' local_administrator
 
-            drush user:create patron --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'patron' patron
+    #         drush user:create patron --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'patron' patron
 
-            drush user:create graphql_consumer --password="$PR_DRUPAL_PWD"
-            drush user:role:add 'graphql_consumer' graphql_consumer
-          else
-            echo "Test users already exist. Skipping creation..."
-          fi
-        service: cli
-    - run:
-        name: Enable example content
-        command: |
-          source dev-scripts/lagoon-error-handling.sh
+    #         drush user:create graphql_consumer --password="$PR_DRUPAL_PWD"
+    #         drush user:role:add 'graphql_consumer' graphql_consumer
+    #       else
+    #         echo "Test users already exist. Skipping creation..."
+    #       fi
+    #     service: cli
+    # - run:
+    #     name: Enable example content
+    #     command: |
+    #       source dev-scripts/lagoon-error-handling.sh
 
-          drush en -y dpl_example_content
-        service: cli
+    #       drush en -y dpl_example_content
+    #     service: cli
     - run:
         name: Setting Deployment status success
         command: |
